backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
logo_url: /images/devfair-logo.svg
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Index"
        name: "index"
        file: "content/index.md"
        fields:
          - label: "Hero"
            name: "hero"
            widget: "object"
            collapsed: false
            fields:
              - { label: "Heading", name: "heading", widget: "markdown" }
              - { label: "Detail", name: "detail", widget: "markdown" }
              - { label: "Hero Image", name: "image", widget: "image", default: "/images/hero.svg" }
